# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
