# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtpages_rest', '0002_auto_20170328_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
